### ISSUE TITLE
how to run the project?

### ISSUE THREAD

**Issue by aishoot** [etzinis/unsupervised_spatial_dc#1]
Hi, thanks for your code sharing and I'm very interested in your study. But how to run the project? Can you give an explanation? @etzinis

**Comment by etzinis** [comment]
Hi,

First you have to generate the data with timit (check data generator) ->
Then you store all the masks, wav recordings, etc in one folder (check
inside the script for paths)

Then you run inside dnn/experiment the experiment script (check the
parameters inside the script -- you have to specify the dataset you have
created above as input)

**Comment by aishoot** [comment]
Thanks. Got it

**Comment by adioleope** [comment]
Hi, I was a little confused about these directories in config.py and what these specified. May I know if it needs changing to what I should change/modify? 

`
import os

os.environ["CUDA_VISIBLE_DEVICES"] = "1,2,3"

BASE_PATH = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TIMIT_PATH = "/mnt/data/Speech/timit-wav"
DATASETS_DIR = "/mnt/nvme/spatial_two_mics_data/"
MODELS_DIR = "/mnt/nvme/spatial_two_mics_models/"
RESULTS_DIR = "/mnt/nvme/spatial_two_mics_results/"
MODELS_RAW_PHASE_DIR = "/mnt/nvme/spatial_two_mics_models_raw_phase/"
MODELS_GROUND_TRUTH = "/mnt/nvme/spatial_two_mics_models_ground_truth/"
FINAL_RESULTS_DIR = "/mnt/nvme/spatial_two_mics_final_eval_results/"
`

**Comment by etzinis** [comment]
just point to the right directories for all the above.
Effectively you only need to alter TIMIT_PATH = "/mnt/data/Speech/timit-wav"
